baseURL = "https://authumn-me.github.io/"
languageCode = "nl-be"
title = "Authumns blog"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "whoami"
    url = "/whoami/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Archief"
    url = "/archives/"
    weight = 4
