baseURL = "https://authumn-me.github.io/"
languageCode = "nl-be"
title = " "
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  label.icon = "/images/logo.png"
  label.iconHeight = 152
  disableImageProcessing = true

[menu]
  [[menu.main]]
    name = "whoami"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blogs"
    url = "/blog"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
