baseURL = "https://authumn-me.github.io/"
languageCode = "nl-be"
title = " "
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  label.icon = "/images/logo.png"
  label.iconHeight = 152
  disableImageProcessing = true
  favicon = "/icons/favicon.ico"
  favicon16x16 = "/icons/favicon-16x16.png"
  favicon32x32 = "/icons/favicon-32x32.png"
  apple_touch_icon = "/icons/apple-touch-icon.png"
  safari_pinned_tab = "/icons/favicon-32x32.png"

[menu]
  [[menu.main]]
    name = "whoami"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blogs"
    url = "/blog"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
